### ISSUE TITLE
eliminating the need for linked CSS

### ISSUE THREAD

**Issue by greatgraphicdesign** [ashmaroli/jekyll#40]
The Use Case: I'm challenged to reduce the number of server requests by eliminating linked CSS tags. However, I love the built-in SCSS preprocessor and importing multiple SCSS snippets into one SCSS file. I would like to keep using SCSS, but the final output CSS file from the SCSS preprocessor is placed in the _site folder. Also, includes do not work with css (or js) extension files.

To eliminate linked files, I currently have to manually copy and paste the processed CSS into an html file in the _includes folder. I would prefer Jekyll do this for me. 

1) I would like to see a property in the ```config.yml``` file that can specify the scss -> css output file folder.
```
sass:
  sass_dir: _sass
  css_dir: _includes
  style: compressed
```

2) I would like Jekyll to be able to include css and js files if they are stored in the _includes folder. So instead of this,
```
<link rel="stylesheet" href="/assets/css/main.css">
```
... we can have this,
```
{% include main.css %}
```

**Comment by ashmaroli** [comment]
Hello @greatgraphicdesign 
First of all, you have opened the ticket in the wrong repository. The real repository is at github.com/jekyll/jekyll.

Nevertheless regarding your feature-request, I would like to inform you about the technical roadblocks involved in your suggestion before you open a ticket at the main repo.

- The `sass` config applies only to the *preprocesser* that we call [sass | scss]-converter. It cannot tell Jekyll where to output the generated `.css` file.
- Jekyll does stuff in distinct phases. *It first reads all files on disk, then converts the contents into desired outputs and finally writes all the files onto disk. You may visually gauge this by building you site with the `--verbose` / `-V` CLI flag.
- The `_includes` directory is accessed during the conversion phase, that is, before Jekyll writes files into the `_site`. So, even if we found a way to drop your CSS file into `_includes`, it's not going to be fruitful.

Ultimately, the `*.scss` source file you have in your theme / assets directory is a `Jekyll::Page` object that resides in the list `site.pages`. Fortunately, there's even a built-in `scssify` / `sassify` Liquid filters that you can use in your templates.
So, assuming your source stylesheet is at path `assets/css/styles.scss`, then **theoretically**, the following should work without any configuration changes:
```
<style>
  {% for item in site.pages %}
  {% if item.path == 'assets/css/styles.scss' %}
  {{ item.content | scssify }}
  {% endif %}
  {% endfor %}
</style>
```

**Comment by greatgraphicdesign** [comment]
Hi @ashmaroli! Thanks so much for your detailed reply, and my apologies for posting in the wrong repository. That liquid filter will work great! I'm very glad to have a solution.
